sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t sle-doc-image .
  # list the installed packages (just for easier debugging)
  - docker run --rm -it sle-doc-image rpm -qa | sort

script:
  - docker run --rm -it sle-doc-image find . -maxdepth 1 -name 'DC-*-all' -exec echo "Validating {}..." \; -exec daps -d \{\} validate --remarks \;
