sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t sle-doc-image .
  # list the installed packages (just for easier debugging)
  - docker run --rm -it sle-doc-image rpm -qa | sort

script:
  # Validating with remarks is the same as validating without, since remarks are
  # not profiled away but just ignored by the stylesheets.
  - docker run --rm -it sle-doc-image /bin/bash -c 'mkdir -p /root/.config/daps/;mkdir -p /root/.config/daps/; echo DOCBOOK5_RNG_URI="https://github.com/openSUSE/geekodoc/raw/master/geekodoc/rng/geekodoc5-flat.rnc" > /root/.config/daps/dapsrc; for dc_file in `ls DC-*-all`; do echo "Validating $dc_file ..."; daps -vv -d $dc_file validate || exit 1; wait; done'
